### ISSUE TITLE
Incorporate TN93 code?

### ISSUE THREAD

**Issue by sdwfrost** [veg/BioExt#15]
I refactored TN93 as a vanilla C file, and Cythonised the function to computeTN93 ([libtn93](https://github.com/sdwfrost/libtn93)). Given that BioExt is already on pip etc., perhaps it would be a good idea to include?

**Comment by stevenweaver** [comment]
Hi @sdwfrost, 

I agree that we should include this in BioExt. My plan is to directly copy what you have in libtn93 into BioExt. If that is the case, a manual pull request will need to be made to bioext any time you wish to update its tn93 code. 

I believe using a submodule to link to the libtn93 repo (especially not under @veg's supervision) in this case could lead to more confusion than convenience.

**Comment by sdwfrost** [comment]
Agreed re: not having a submodule. It's better to have it all under one bioext umbrella. Happy to submit PRs if needs be.

**Comment by stevenweaver** [comment]
Excellent. This task is almost complete. There is a small issue with the gcc build at the moment that I did not catch upon initial merge.

**Comment by stevenweaver** [comment]
The task is complete via Github. There is a small build error within pypi at the moment. I may not be able to resolve the pypi package situation until tomorrow morning.

**Comment by stevenweaver** [comment]
TN93 has been integrated into the BioExt package with version 0.19.1. Please revert to using bioext.

```
pip uninstall biopython-extensions
pip install bioext
```

**Comment by sdwfrost** [comment]
Great @stevenweaver. Will give it a try.

**Comment by stevenweaver** [comment]
Great. I placed your tests [here](https://github.com/veg/BioExt/blob/master/tests/tn93.py).

You can import from BioExt like so:
```
from BioExt.tn93 import tn93
```

and use it the same way as in libtn93.
