### ISSUE TITLE
translate_ambiguous needs updating

### ISSUE THREAD

**Issue by sdwfrost** [veg/BioExt#32]
`translate_ambiguous` no longer works, as `Seq` no longer as a method `tostring()`, instead, one uses `str(seq)` to get the string representation.

**Comment by stevenweaver** [comment]
Dear @sdwfrost, 

Thank you for reporting this issue. The issue is resolved in `0.19.6` and has been published to pypi. 

Best,
Steven

**Comment by sdwfrost** [comment]
Thanks @stevenweaver!
