### ISSUE TITLE
BUG: Installation fails on Python 3.11

### ISSUE THREAD

**Issue by FynnFreyer** [veg/BioExt#50]
This is a crosspost from [hivtrace#84](https://github.com/veg/hivtrace/issues/84), and doesn't have any new informaton.
This is just to have the info in the right repo as well. After rereading, I think this is probably not directly related to #26.

# Steps to reproduce

- install python 3.11
- generate a clean venv (`python -m venv venv && source venv/bin/activate`)
- install numpy (more on that in another issue)
- A) reproduce from pypi
  - install (`pip install bioext`)
- B) reproduce from local repo
  - clone (`git clone https://github.com/veg/BioExt`)
  - install (`pip install ./BioExt`)

## Expected behaviour

pip installs the package

## Actual behaviour

pip fails to install the package

# Suspicion

A little digging leads me to believe that the reason for this is that the Python C API changed after 3.8, which is why the Extensions for BioExt can't find "longintrepr.h", and fail to compile. 

Another issue is that NumPy 1.20.3 (which is [EOL](https://numpy.org/neps/nep-0029-deprecation_policy.html)) just doesn't support 3.11.

When cloning the BioExt Repo, commenting out the extensions (except `tn93_extension`), bumping the numpy version to 1.22 (also EOL, but supports Python 3.11) and then installing that, everything installs fine. Unfortunately, removing those extensions is not a solution, but hopefully enough information to fix the problem. When not commenting them out, it fails.

[Cython had a similar issue](https://github.com/cython/cython/issues/4461), but fixed it (which is why the cythonized `tn93_extension` still compiles cleanly even though it uses "longintrepr.h"). Here's the related [discussion on the Python bugtracker](https://bugs.python.org/issue35134)

Also, here's a minimal git patch to ease verification for you (GitHub unfortunately doesn't allow attaching these as a file).

```diff
diff --git a/setup.py b/setup.py
index 45a3fd2..eb33561 100644
--- a/setup.py
+++ b/setup.py
@@ -22,32 +22,6 @@ tn93_extension = cythonize([
         )])
 
 ext_modules = [
-    Extension(
-        'BioExt.align._align',
-        sources=[
-            os.path.join('BioExt', 'align', '_align.c'),
-            os.path.join('BioExt', 'align', 'alignment.c')
-            ],
-        include_dirs=np_inc,
-        libraries=['m'],
-        extra_compile_args=['-O3', '-I.']
-        ),
-    Extension(
-        'BioExt.merge._merge',
-        sources=[
-            os.path.join('BioExt', 'merge', '_merge.c'),
-            os.path.join('BioExt', 'merge', 'merge.cpp')
-            ],
-        extra_compile_args=['-O3', '-I.']
-        ),
-    Extension(
-        'BioExt.rateclass._rateclass',
-        sources=[
-            os.path.join('BioExt', 'rateclass', '_rateclass.cpp'),
-            os.path.join('BioExt', 'rateclass', 'rateclass.cpp')
-            ],
-        extra_compile_args=['-O3', '-I.']
-        )
     ] + tn93_extension
 
 
@@ -134,7 +108,7 @@ setup(
     ext_modules=ext_modules,
     install_requires=[
         'biopython >=1.78',
-        'numpy ==1.20.3',
+        'numpy ==1.22.4',
         'scipy >=0.15',
         'pysam >=0.17',
         'joblib',
```

**Comment by stevenweaver** [comment]
Resolved in 1.21.1
