### ISSUE TITLE
Does not work with pysam >= 0.9

### ISSUE THREAD

**Issue by ericenns** [veg/BioExt#6]
pysam.sort has changed, look at https://github.com/pysam-developers/pysam/issues/291

**Comment by ericenns** [comment]
I see you have it in the setup.py for 0.17.4, I was installing 0.17.3.

**Comment by stevenweaver** [comment]
Hi Eric,

I see now. 
I will keep this ticket open until we update BioExt to be compatible with pysam >=0.9, however.

Best,
Steven

**Comment by stevenweaver** [comment]
Due to this bug - https://github.com/pysam-developers/pysam/issues/308, I believe pysam 0.9.x to be a bit unstable at the moment. I'm closing this issue and will revisit making BioExt compatible with pysam 0.9.x when development seems more stable.

**Comment by sdwfrost** [comment]
Hi @stevenweaver ; my code is using the latest pysam, which fixes the issue, but is incompatible with the current bioext. Do you have a timeline for compatibility tweaks to work? Thanks!

**Comment by stevenweaver** [comment]
Hi @sdwfrost, 

I will take time to do it early this week. I am also very excited about the latest TN93 developments. Updating the sort function for compatibility with pysam 0.9.x should be trivial to do.

**Comment by stevenweaver** [comment]
Dear #sdwfrost,

BioExt 0.18.6 uses pysam >0.9. You should be able to update your current version of bioext through pip. I am looking into incorporating the TN93 library now.

**Comment by sdwfrost** [comment]
Thanks @stevenweaver ! Can you add a note to the README.md that it's registered in pip under `biopython-extensions`? @nlhepler 's old version is registered under BioExt...

**Comment by stevenweaver** [comment]
Dear @sdwfrost,

Yes, will do. Sorry about this situation, I've requested that @nlhepler transfer ownership on pypi or help but I think there might have been some miscommunication between us.

**Comment by stevenweaver** [comment]
@sdwfrost, bioext write access has been given to the @veg pypi group. I will keep biopython-extensions as an alias, but bioext should work henceforth. Thanks @nlhepler!
