### ISSUE TITLE
_align_par fails due to SeqRecord Comparison

### ISSUE THREAD

**Issue by sdwfrost** [veg/BioExt#9]
In the [aligner](https://github.com/veg/BioExt/blob/a81561079fcfe3599e58a4530c4028f115c21e27/BioExt/align/__init__.py)

Line 225 throws an error with BioPython 1.68, as one cannot compare SeqRecords.

```
        if len(ref) and ref == query:
```

Changing the line to this seems to work:

```
        if len(ref) and ref == str(query.seq):
```

**Comment by spond** [comment]
Dear Simon,

Thanks for this report and fix. So much for semantic versioning not breaking APIs?  Boo @ BioPython :)

Steven is preparing an updated release, and he will roll this into the update.

Sergei
